//
//  dancasinfo.swift
//  appdedancinha
//
//  Created by filhota on 09/06/23.
//

import Foundation
struct dancasinfo : Identifiable {
      
    var id : Int
    var name : String
    var image : String
    var details : String
    var url: URL
}
    var dancelist = [
        
        dancasinfo(id: 0, name: "Axé", image: "axé", details: "História:  O axé, ou axé music, é um gênero musical que surgiu no estado da Bahia na década de 1980 durante as manifestações populares do Carnaval de Salvador, misturando o ijexá, samba-reggae, frevo, reggae, merengue, forró, samba duro, ritmos do candomblé, pop rock, bem como outros ritmos afro-brasileiros e afro-latinos.",url:URL(string:"https://www.youtube.com/watch?v=h-csANguffc")!),
        dancasinfo(id: 1, name: "Baião", image: "baiao", details: "História: O baião é um gênero musical originário do Nordeste do Brasil, influenciado pelas danças folclóricas africanas lundu, coco, calango e batuque, que chegaram ao país, no século XVI. Musicalmente, o baião exibiu traços do tango brasileiro, do maracatu, do cateretê e do coco. O termo “baião”, originalmente “baiano”, referia‐se a uma dança de roda com desafios vocais improvisados. Era comum a presença de um violão, juntamente, com o canto.",url:URL(string:"https://www.youtube.com/watch?v=F-bK-XZZQyE")!),
        dancasinfo(id: 2, name: "Carimbó", image: "Carimbo", details: "História: O carimbó é uma dança cultural da região Norte, que teve origem no estado do Pará durante o século XVII,  a partir das danças e costumes indígenas. O nome é em homenagem ao instrumento musical indígena curimbó, tambor artesanal utilizado em apresentações artísticas e religiosas.  A junção de cur (pau oco) e m’bó (furado) significa em português: pau que produz o som. ",url:URL(string:"https://www.youtube.com/watch?v=Dq0NgYpmgFU")!),
        dancasinfo(id: 10, name: "Coco de Roda", image: "coco-de-roda", details:"Sua origem data do século XVI, onde acredita-se que tenha surgido dentro dos engenhos e depois levado para o litoral. Foi criado a partir dos batuques e umbigadas de origem africana, além das trocas de experiências com indígenas. Outra crença, é de que que o ritmo tenha surgido através do canto dos tiradores de coco no ambiente de trabalho e depois, com a popularização, passou a ser dançado. O coco pode ser dançado em pares, filas ou rodas e suas características mais marcantes são as batidas dos pés – descalços ou com calçados de madeira – que imitam o barulho do coco sendo quebrado, as expressões corporais e palmas. Uma figura importante dentro do coco de roda é o coquista, ou mestre “cantadô”, que puxa versos já conhecidos pelos participantes ou improvisados.",url:URL(string:"https://www.youtube.com/watch?v=Jy63IOByJQw")!),
        dancasinfo(id: 3, name: "Forró", image: "Forro1", details: "História: O forró surgiu em meados da década de 1930, popularizando-se por volta dos anos 1950 por todo o Brasil através do poeta, cantor e compositor Luiz Gonzaga (1912 -1989), que convencionou o formato do trio de forró composto pelos instrumentos musicais sanfona, zabumba e triângulo. Outros fatores como a migração nordestina para o sudeste, a divulgação midiática nas rádios e o interesse comercial das gravadoras, contribuíram para a popularização do estilo musical.",url:URL(string:"https://www.youtube.com/watch?v=FQQ9NBYKfIY")!),
        dancasinfo(id: 4, name: "Frevo", image: "frevo", details: "História: O frevo é uma manifestação folclórica brasileira típica do estado de Pernambuco, sendo uma das principais manifestações culturais do estado. Ele é característico do Carnaval de rua do estado, em especial nas cidades de Olinda e Recife. Surgiu no século XIX e é caracterizado pelas músicas com ausência de letras e por uma dança que usa pequenos guarda-chuvas coloridos como elementos da coreografia. O termo vem do verbo ferver, cujo sentido, nesse caso, se relaciona com o ritmo frenético executado pelos dançarinos.",url:URL(string:"https://www.youtube.com/watch?v=A1aGURlQP6A")!),
        dancasinfo(id: 5, name: "Lambada", image: "Lambada", details: "História: O ritmo da lambada possui movimentos sensuais e românticos, e se dança de em pares, casais. O ritmo se originou no norte do Brasil, mais precisamente no estado do Pará, mas logo se tornou popular em todo o país e foi uma verdadeira febre dos anos 80. essa famosa dança brasileira é uma mistura de vários outros ritmos brasileiros já existentes, como o forró e o carimbó em conjunto com tantos outros ritmos latino-americanos, como o merengue e a cumbia.",url:URL(string:"https://www.youtube.com/watch?v=uZH_U1cEn8s")!),
        dancasinfo(id: 6, name: "Maracatu", image: "Maracatu", details: "História: O Maracatu é um dos ritmos populares mais importantes do Nordeste. Surgiu em meados de XVIII no estado de Pernambuco durante o período em que pessoas negras ainda eram escravizadas. É um movimento da cultura popular que envolve música, dança e história - além de figurinos extravagantes, que remetem à cultura africana, indígena e portuguesa.",url:URL(string:"https://www.youtube.com/watch?v=P8TLn4APN5o")!),
        dancasinfo(id: 7, name: "Piseiro", image: "Piseiro", details: "História: Nasceu no interior do Nordeste nos anos 2010. Essa vertente do forró se caracteriza por substituir a superestrutura de uma banda complexa pelo teclado eletrônico.Uma curiosidade diz respeito à dança da pisadinha, no começo as pessoas dançavam juntas como no forró convencional. Porém, com o passar do tempo, se criou o hábito de que grupos de amigos se reunissem para dançar sozinhos, cada qual a seu modo. Essa é uma das marcas do gênero.",url:URL(string:"https://www.youtube.com/watch?v=7Mo-ix6inNw")!),
        dancasinfo(id: 8, name: "Samba", image: "Samba2", details: "História: O samba surgiu no começo do século XX e é uma influência da cultura africana em nosso país. Tem uma ligação com as rodas de dança que os negros escravizados realizavam nos seus poucos momentos livres. Essas rodas de dança, geralmente, eram puxadas por um ritmo musical obtido por meio dos batuques. Uma das danças mais praticadas era o lundu, que, acredita-se, foi introduzida aqui por africanos trazidos da Angola.Uma das variantes dessas rodas de dança era o samba de roda, um estilo musical que reunia africanos escravizados para praticar danças e capoeira. Esse estilo musical surgiu na Bahia, em meados do século XIX, e foi um dos precursores do samba tradicional (conhecido como samba urbano carioca). O samba de roda também tem uma ligação direta com as práticas rituais de culto aos orixás.",url:URL(string:"https://www.youtube.com/watch?v=Tjh1wq24kTk")!),
        dancasinfo(id: 9, name: "Siriá", image: "Siria", details: "História: A dança do siriá tem suas raízes nas tradições indígenas e afrodescendentes da região amazônica. É uma dança coletiva, executada em grupo, onde os dançarinos se movimentam em círculos ao som de tambores, flautas e outros instrumentos típicos da região. A música é alegre, ritmada e contagiante, refletindo a energia da natureza e a vida ribeirinha amazônica. A dança do siriá está ligada a celebrações e rituais relacionados à pesca, colheita e festividades religiosas. Era comum que comunidades ribeirinhas se reunissem para dançar o siriá como forma de agradecimento e celebração pelos recursos naturais e pela abundância da região.",url:URL(string:"https://www.youtube.com/watch?v=qjGAKE--agM")!),
        
    ]
var dancasanimadas = [ dancasinfo(id: 0, name: "Baião", image: "baiao", details:"História: O baião é um gênero musical originário do Nordeste do Brasil, influenciado pelas danças folclóricas africanas lundu, coco, calango e batuque, que chegaram ao país, no século XVI. Musicalmente, o baião exibiu traços do tango brasileiro, do maracatu, do cateretê e do coco. O termo “baião”, originalmente “baiano”, referia‐se a uma dança de roda com desafios vocais improvisados. Era comum a presença de um violão, juntamente, com o canto.",url:URL(string:"https://www.youtube.com/watch?v=F-bK-XZZQyE")!), dancasinfo(id: 1, name: "Forró", image: "Forro1", details: "História: O forró surgiu em meados da década de 1930, popularizando-se por volta dos anos 1950 por todo o Brasil através do poeta, cantor e compositor Luiz Gonzaga (1912 -1989), que convencionou o formato do trio de forró composto pelos instrumentos musicais sanfona, zabumba e triângulo. Outros fatores como a migração nordestina para o sudeste, a divulgação midiática nas rádios e o interesse comercial das gravadoras, contribuíram para a popularização do estilo musical.",url:URL(string:"https://www.youtube.com/watch?v=FQQ9NBYKfIY")!),]
var dancasdecasal = [dancasinfo(id: 0, name: "Lambada", image: "Lambada", details: "História: O ritmo da lambada possui movimentos sensuais e românticos, e se dança de em pares, casais. O ritmo se originou no norte do Brasil, mais precisamente no estado do Pará, mas logo se tornou popular em todo o país e foi uma verdadeira febre dos anos 80. essa famosa dança brasileira é uma mistura de vários outros ritmos brasileiros já existentes, como o forró e o carimbó em conjunto com tantos outros ritmos latino-americanos, como o merengue e a cumbia.",url:URL(string:"https://www.youtube.com/watch?v=uZH_U1cEn8s")!), dancasinfo(id: 1, name: "Siriá", image: "Siria", details: "História: A dança do siriá tem suas raízes nas tradições indígenas e afrodescendentes da região amazônica. É uma dança coletiva, executada em grupo, onde os dançarinos se movimentam em círculos ao som de tambores, flautas e outros instrumentos típicos da região. A música é alegre, ritmada e contagiante, refletindo a energia da natureza e a vida ribeirinha amazônica. A dança do siriá está ligada a celebrações e rituais relacionados à pesca, colheita e festividades religiosas. Era comum que comunidades ribeirinhas se reunissem para dançar o siriá como forma de agradecimento e celebração pelos recursos naturais e pela abundância da região.",url:URL(string:"https://www.youtube.com/watch?v=qjGAKE--agM")!)]

